/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    categories: Category;
    tags: Tag;
    'content-queue': ContentQueue;
    lots: Lot;
    'lot-amenities': LotAmenity;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'content-queue': ContentQueueSelect<false> | ContentQueueSelect<true>;
    lots: LotsSelect<false> | LotsSelect<true>;
    'lot-amenities': LotAmenitiesSelect<false> | LotAmenitiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  /**
   * Brief summary for SEO and post previews (max 300 chars)
   */
  excerpt: string;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: number | Category;
  tags?: (number | Tag)[] | null;
  author: number | User;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  /**
   * Set ONLY when article content is genuinely refreshed (blog engine regeneration or a real editorial update). Drives the visible "Updated" date, JSON-LD dateModified, and sitemap lastmod on the site. Leave blank for SEO scoring, link passes, or other non-content saves — unlike updatedAt, this must not bump automatically. Note: the site only shows the badge when this is >24h after publishedAt, so a same-day stamp will not display.
   */
  contentUpdatedAt?: string | null;
  seo?: {
    /**
     * Override title for search engines (max 60 chars)
     */
    metaTitle?: string | null;
    /**
     * Description for search engines (max 160 chars)
     */
    metaDescription?: string | null;
  };
  /**
   * SEO score (0-100) — run blog-engine score command to update
   */
  seoScore?: number | null;
  /**
   * Full SEO scoring breakdown — updated by the blog engine score command
   */
  seoScoreDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Airport IATA code (e.g., JFK, LGA)
   */
  airportCode?: string | null;
  /**
   * Topic cluster tier for SEO content
   */
  articleType?: ('hub' | 'sub-pillar' | 'spoke') | null;
  /**
   * Parent article slug (for sub-pillars and spokes)
   */
  parentSlug?: string | null;
  /**
   * Hub article slug for the airport cluster
   */
  hubSlug?: string | null;
  /**
   * FAQ items for accordion display and schema markup
   */
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-queue".
 */
export interface ContentQueue {
  id: number;
  /**
   * Focus keyword — drives the URL slug, AI-generated title, and all content. This is the exact search query we want to rank for.
   */
  keyword: string;
  /**
   * Airport IATA code (e.g., JFK, LGA)
   */
  airportCode: string;
  /**
   * URL slug for the generated article
   */
  slug: string;
  /**
   * Topic cluster tier
   */
  articleType: 'hub' | 'sub-pillar' | 'spoke';
  /**
   * Controls article opening structure and tone variation
   */
  articleStyle?: ('standard' | 'narrative' | 'listicle' | 'data-heavy' | 'comparison') | null;
  /**
   * Parent article slug (for sub-pillars and spokes)
   */
  parentSlug?: string | null;
  /**
   * Hub article slug for the airport cluster
   */
  hubSlug?: string | null;
  /**
   * Monthly search volume estimate
   */
  searchVolume?: number | null;
  /**
   * SEO difficulty score (0-100)
   */
  seoDifficulty?: number | null;
  /**
   * Target word count for the article
   */
  targetWords?: number | null;
  priority: 'S1' | 'S2' | 'S3';
  status: 'queued' | 'generating' | 'draft' | 'review' | 'published' | 'error';
  /**
   * Batch group name (e.g., "week-1", "jfk-launch")
   */
  batch?: string | null;
  /**
   * Scheduled publish date for batch publishing
   */
  scheduledPublishDate?: string | null;
  /**
   * URLs of competitor articles to analyze
   */
  competitorUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Article outline (headings and structure)
   */
  outline?:
    | {
        order: number;
        /**
         * HTML anchor ID for this section
         */
        anchorId?: string | null;
        heading: string;
        /**
         * Brief description of section content
         */
        summary?: string | null;
        /**
         * Slug of article this section should link to
         */
        linksTo?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The generated blog post (set automatically)
   */
  generatedPost?: (number | null) | Post;
  /**
   * Error details if generation failed
   */
  errorMessage?: string | null;
  /**
   * Internal notes about this queue item
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Lots that sell through Triply directly (no Reservations Lab). Admin-only to edit. A lot is bookable only when status = published, isActive is on, and its visibility matches the environment.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lots".
 */
export interface Lot {
  id: number;
  name: string;
  /**
   * URL path segment. Generated from the name if left blank. Lowercase letters, digits and hyphens; cannot be all digits or start with "reslab-"/"direct-" (a name starting with "Direct …" needs a hand-written slug).
   */
  slug: string;
  /**
   * IATA code the lot serves, UPPERCASE, e.g. LGA. Must match an airport the site lists.
   */
  airportCode: string;
  /**
   * Only if this same lot ALSO exists on Reservations Lab: its ResLab location id. The ResLab listing is then hidden so the lot is not shown twice.
   */
  reslabLocationId?: number | null;
  /**
   * Short blurb for search results (max 250 chars)
   */
  descriptionShort?: string | null;
  featuredImage?: (number | null) | Media;
  /**
   * Additional photos shown on the lot page. (A media item used here cannot be deleted while referenced.)
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  amenities?: (number | LotAmenity)[] | null;
  /**
   * Approximate shuttle/walk time to the terminal, in minutes
   */
  distanceToTerminalMinutes?: number | null;
  /**
   * Shuttle hours and frequency as shown to the customer on the lot page and in the confirmation email (e.g. "Runs every 15 min, 4 AM – 1 AM"). Leave blank if there is no shuttle.
   */
  shuttleDetails?: string | null;
  /**
   * Shuttle/lot contact phone shown in the confirmation email.
   */
  shuttlePhone?: string | null;
  /**
   * Required: the confirmation email and Park Guard enrolment both need a full address.
   */
  address: {
    street: string;
    city: string;
    /**
     * 2-letter code, UPPERCASE (e.g. NY)
     */
    state: string;
    zip: string;
  };
  /**
   * Required: map pin, distance to the airport, and airport attribution.
   */
  coordinates: {
    lat: number;
    lng: number;
  };
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Lot-specific sections for the confirmation email. Plain text per section: lines starting with "- " render as bullets. Empty sections are omitted.
   */
  bookingInstructions?: {
    /**
     * "Before Arrival" — forms or reminders.
     */
    beforeArrival?: string | null;
    /**
     * "When You Arrive" — check-in / key-drop procedure.
     */
    whenYouArrive?: string | null;
    /**
     * "Important Notes" — restrictions (vehicle size, oversize fees). Shown highlighted.
     */
    importantNotes?: string | null;
    /**
     * "When You Return" — pickup procedure.
     */
    whenYouReturn?: string | null;
    /**
     * "Getting to and from the Airport" — shuttle details or alternatives.
     */
    gettingToAirport?: string | null;
  };
  /**
   * Must be on for the lot to appear in search or be bookable.
   */
  isActive?: boolean | null;
  /**
   * "staging_only" = visible on staging/preview/local only (test lots; the CMS is shared by every environment). "production" = visible everywhere. Staging-only lots may only notify @triplypro.com addresses.
   */
  visibility: string;
  /**
   * Minimum billed days per booking (whole number).
   */
  minStayDays?: number | null;
  /**
   * Earliest drop-off accepted, in hours from now. Gives the lot time to see the booking email (default 2).
   */
  minLeadHours?: number | null;
  /**
   * Price per billed day in USD (2 decimals), before tax and before the Triply service fee. Billing is in 24-hour periods from drop-off to pickup.
   */
  baseDailyRate: number;
  /**
   * Oversized-vehicle surcharges, PAID AT THE LOT (never charged online). The customer picks one when they reserve; "No oversized vehicle" is always offered and is not a row here. Tax on the surcharge is also paid at the lot, at this lot's tax rate. Leave empty if the lot has no surcharges. A bad row takes the lot offline on the site, so every row is checked on save.
   */
  vehicleSurcharges?:
    | {
        /**
         * Stable id stored on bookings, e.g. small_suv. Lowercase letters, digits and underscores; unique within the lot; never "none". Do not change it once bookings exist.
         */
        code: string;
        /**
         * What the customer sees, e.g. "Large SUV / truck".
         */
        label: string;
        /**
         * USD per billed day, before tax (2 decimals). Billed on the same days as the parking.
         */
        dailyRate: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Parking tax applied to the parking subtotal, as a percentage (e.g. 18.375). Required — enter 0 only if confirmed with the accountant.
   */
  taxRatePercent: number;
  /**
   * "triply" = Triply collects the tax online and remits it. "lot" = the tax is passed through to the lot in its payout. Required; no default on purpose.
   */
  taxCollectedBy: string;
  /**
   * Share of the parking subtotal paid out to the lot, as a percentage (e.g. 80).
   */
  partnerSharePercent: number;
  /**
   * Where the lot receives each booking and cancellation notice (and the daily manifest). At least one. For a staging_only lot these must all be @triplypro.com.
   */
  notificationEmails: {
    email: string;
    id?: string | null;
  }[];
  /**
   * Draft lots are never shown or bookable, regardless of isActive.
   */
  status: 'draft' | 'published';
  /**
   * Record only — when the lot first went live. Not used by the site.
   */
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lot-amenities".
 */
export interface LotAmenity {
  id: number;
  /**
   * Display name (e.g. "EV Charging", "Covered Parking", "Shuttle to Terminal")
   */
  name: string;
  /**
   * Icon token used by the site icon set (e.g. "plug", "roof")
   */
  icon?: string | null;
  /**
   * Short tooltip description (optional)
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'content-queue';
        value: number | ContentQueue;
      } | null)
    | ({
        relationTo: 'lots';
        value: number | Lot;
      } | null)
    | ({
        relationTo: 'lot-amenities';
        value: number | LotAmenity;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  category?: T;
  tags?: T;
  author?: T;
  status?: T;
  publishedAt?: T;
  contentUpdatedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  seoScore?: T;
  seoScoreDetails?: T;
  airportCode?: T;
  articleType?: T;
  parentSlug?: T;
  hubSlug?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-queue_select".
 */
export interface ContentQueueSelect<T extends boolean = true> {
  keyword?: T;
  airportCode?: T;
  slug?: T;
  articleType?: T;
  articleStyle?: T;
  parentSlug?: T;
  hubSlug?: T;
  searchVolume?: T;
  seoDifficulty?: T;
  targetWords?: T;
  priority?: T;
  status?: T;
  batch?: T;
  scheduledPublishDate?: T;
  competitorUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  outline?:
    | T
    | {
        order?: T;
        anchorId?: T;
        heading?: T;
        summary?: T;
        linksTo?: T;
        id?: T;
      };
  generatedPost?: T;
  errorMessage?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lots_select".
 */
export interface LotsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  airportCode?: T;
  reslabLocationId?: T;
  descriptionShort?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  content?: T;
  amenities?: T;
  distanceToTerminalMinutes?: T;
  shuttleDetails?: T;
  shuttlePhone?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  bookingInstructions?:
    | T
    | {
        beforeArrival?: T;
        whenYouArrive?: T;
        importantNotes?: T;
        whenYouReturn?: T;
        gettingToAirport?: T;
      };
  isActive?: T;
  visibility?: T;
  minStayDays?: T;
  minLeadHours?: T;
  baseDailyRate?: T;
  vehicleSurcharges?:
    | T
    | {
        code?: T;
        label?: T;
        dailyRate?: T;
        id?: T;
      };
  taxRatePercent?: T;
  taxCollectedBy?: T;
  partnerSharePercent?: T;
  notificationEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lot-amenities_select".
 */
export interface LotAmenitiesSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}